version: '3'

volumes:
  postgres_data:
    driver: local
    name: weather_postgres

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    networks:
      wnet:
        ipv4_address: 172.20.0.5

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    volumes:
      - ./tmp/import:/tmp/import
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.realmName=weather-test"
      - "-Dkeycloak.migration.usersExportStrategy=REALM_FILE"
      - "-Dkeycloak.migration.file=/tmp/import/realm-import.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: 12345
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8181:8080
    depends_on:
      - postgres
    networks:
      wnet:
        ipv4_address: 172.20.0.6

  weather:
    container_name: weather-app
    image: pascalcode/weather-app:0.0.1
    ports:
      - 8080:8081
    links:
      - postgres:postgres
      - keycloak:keycloak
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: 172.20.0.5
      KEYCLOAK_PORT_8080_TCP_ADDR: 172.20.0.6
      KEYCLOAK_PORT_8080_TCP_PORT: 8080
    networks:
      wnet:
        ipv4_address: 172.20.0.7


networks:
  wnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24